config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "articles#index"
  
#   get "/articles", to: "articles#index"
#   get "/articles/:id", to: "articles#show"
  resources :articles do
	resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
# class Article < ApplicationRecord
# 	has_many :comments
  
# 	validates :title, presence: true
# 	validates :body, presence: true, length: { minimum: 10 }
#   end

class Article < ApplicationRecord
	include Visible
  
	has_many :comments, dependent: :destroy
  
	validates :title, presence: true
	validates :body, presence: true, length: { minimum: 10 }
  end
  

app/models/comment.rb
# class Comment < ApplicationRecord
#   belongs_to :article
# end

class Comment < ApplicationRecord
	include Visible
	belongs_to :article
  end
  

app/models/concerns/visible.rb
module Visible
	extend ActiveSupport::Concern
  
	VALID_STATUSES = ['public', 'private', 'archived']
  
	included do
	  validates :status, inclusion: { in: VALID_STATUSES }
	end
  
	class_methods do
	  def public_count
		where(status: 'public').count
	  end
	end
  
	def archived?
	  status == 'archived'
	end
  end
  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

	
	http_basic_authenticate_with name: "a", password: "b", except: [:index, :show]
	
  def index
	@articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render :new
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to root_path
  end
  
  private
  def article_params
	params.require(:article).permit(:title, :body, :status)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	http_basic_authenticate_with name: "a", password: "b", only: :destroy

	def create
	  @article = Article.find(params[:article_id])
	  @comment = @article.comments.create(comment_params)
	  redirect_to article_path(@article)
	end
  
	def destroy
	  @article = Article.find(params[:article_id])
	  @comment = @article.comments.find(params[:id])
	  @comment.destroy
	  redirect_to article_path(@article)
	end
  
	private
    def comment_params
      params.require(:comment).permit(:commenter, :body, :status)
    end
  end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
<div class="container p-2">
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %><br>
    <% article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
  <%= form.label :status %><br>
  <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
  </div>

  <div class="mt-3">
    <%= form.submit %>
  </div>
</div>
<% end %>

app/views/articles/edit.html.erb
<%= render 'partials/header' %>

<%# Back to index link %>
<section class="container">
	<div class="row">
		<div class="col-md-12 mt-5">
			<a href="<%= articles_path %>" class="text-dark">Back to Articles</a>
		</div>
	</div>
</section>

<%# Edit form %>
<section class="container mb-5 shadow-sm bg-body rounded">
<h1>Edit Article</h1>

<%= render "form", article: @article %>
</section>

<%= render 'partials/footer' %>

app/views/articles/index.html.erb
<%# <h1>Articles#index</h1>
<p>Find me in app/views/articles/index.html.erb</p> %>

<%# <h1>Hello, Rails!</h1> %>

<%= render 'partials/header' %>

<%# --Title and article count section %>
<section class="container">
	<div class="p-4 p-md-5 mb-4 text-white rounded bg-dark">
	 <div class="col-md-6 px-0">
			<h1 class="display-4 fst-italic">Articles</h1>
			<p class="lead my-3">Our blog has <%= Article.public_count %> articles and counting!</p>
		</div>
	</div>
</section>

<section class="container">
	<div class="row">
		<div class="col-md-12">
			<a href="/articles/new" class="text-dark">Create New Article</a>
		</div>
	</div>
</section>

<%# --Article list section %>
<section class="container p-5 shadow-sm p-3 mb-5 bg-body rounded">
<div class="row g-5">
    <div class="col-md-8">
			<h2 class="pb-4 mb-4 fst-italic border-bottom">
        Topics
      </h2>

			<ul>
				<% @articles.each do |article| %>
					<article class="blog-post mb-5">
							<h2 class="blog-post-title"><%= article.title %></h2>
							<p class="blog-post-meta"><%= article.created_at.strftime("%B %d, %Y") %></p>
							<p><%= article.body.truncate(100) %>
							<p><a href="/articles/<%= article.id %>" class="text-dark">Read More</a></p>
					</article>
				<% end %>
			</ul>

		</div>
</div>
</section>

<%= render 'partials/footer' %>

app/views/articles/new.html.erb
<%= render 'partials/header' %>

<%# Back to index link %>
<section class="container">
	<div class="row">
		<div class="col-md-12 mt-5">
			<a href="<%= articles_path %>" class="text-dark">Back to Articles</a>
		</div>
	</div>
</section>

<%# New form %>
<section class="container mb-5 shadow-sm bg-body rounded">
<h1>New Article</h1>

<%= render "form", article: @article %>
</section>

<%= render 'partials/footer' %>

app/views/articles/show.html.erb
<%= render 'partials/header' %>

<%# Article edit and destroy button %>
<section class="container">
	<div class="row">
		<div class="col-md-12 mt-5">
			<a href="<%= articles_path %>" class="text-dark">Back to Articles</a>
				<a href="<%= edit_article_path(@article) %>" class="text-dark">Edit</a>
				<a href="<%= article_path(@article) %>" class="text-dark" data-confirm="Are you sure?" data-method="delete" class="btn btn-danger">Delete</a>
		</div>
	</div>
</section>


<%# Article title and body %>
<section class="container shadow-sm mb-5 bg-body rounded">
	<h1><%= @article.title %></h1>
		<div class="container p-3">
			<p><%= @article.body %></p>
		</div>
</section>

<%# Article comments %>
<section class="container mt-1">
		<div class="container shadow-sm mb-5 bg-body rounded">
			<h2 class="mb-3">Comments</h2>
				<div class="p-3">
					<%= render @article.comments %>
				</div>
		</div>
</section>

<%# Add comment form %>
<section class="container mb-5">
	<div class="card">
		<div class="card-body">
			<h5 class="card-title">Add a comment:</h5>
			<%= render 'comments/form' %>
		</div>
	</div>
</section>

<%= render 'partials/footer' %>

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>

<p>
  <strong>Comment:</strong>
	<%= comment.body %>
</p>


<p class="text-dark">
  <%= link_to 'Destroy Comment', [comment.article, comment],
              method: :delete,
              data: { confirm: "Are you sure?" } %>
</p>
				
<hr>

app/views/comments/_form.html.erb
<%= form_with model: [ @article, @article.comments.build ] do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
  <%= form.label :status %><br>
  <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/partials/_footer.html.erb
 	</main>
 
 <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/partials/_header.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

		<%# Fontawesome CDN %>
		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body>

	<main class="container">  
	